import { useMemo } from "react";
// import { Equal, Expect } from "../helpers/type-utils";

export const Component = () => {
  const autoGeneratedIds = useMemo(() => {
    // generate 100 random string uuid's
    return Array.from({ length: 100 }, () =>
      Math.random().toString(36).substr(2, 9)
    );
  }, []);

  type test = Expect<Equal<typeof autoGeneratedIds, string[]>>;
};

// used to be useMemo<() => string[]>
// took out the type argument (line 5)
// or could do useMemo((): string[] => { })
